### ISSUE TITLE
Wrong Indention (Too Far Right) of "end" Words Caused by if Statements

### ISSUE THREAD

**Issue by Orionsg** [chriscamicas/vscode-abl#17] opened 2018-05-08 15:56 UTC
When a block of code contains if statements, it apparently confuses the logic that decides the automatic indention for end words.

See the following code:
```
class cls_test:

    method private void tt_info(p_c_text as char):
        if p_c_text = ? or p_c_text = '':u then return.
        create tt_info.
        tt_info.text = p_c_text.<--CURSOR HERE>

end class.
```

If you place the cursor as indicated above, press <Enter> and then type "end." and new line, the end statement is not put correctly at the same indention level as corresponding method statement above.

However, If you remove the first line of the method containing the if statement, it works just fine, i.e. the "end" word's indention is automatically adjusted correctly. 

It took me a while to find the cause as sometimes (seemingly random) an "end" word would be adjusted very far to the right, like four levels in from where it should be. I think the more if statements there are in the block, the more far off to the right the "end" word is indented, but I have not checked this.

**Comment by fabiopicolijr** [comment] 2018-05-20 18:57
@Orionsg I've tested your example and the problem is that the vscode abl don't understand this part of your code: "p_c_text = '':u".

**Comment by Orionsg** [comment] 2018-05-21 05:51
@fabiopicolijr: You are absolutely right: The colon after the two single quote characters causes the wrong indention and not the if statement. 
However, setting attributes on string literals is a quite common practice in ABL when working with translations. Thus it should fixed in the plugin so that ":u", :t, ":r", etc. may be appended as attributes to literal strings.

**Comment by fabiopicolijr** [comment] 2018-05-21 23:08
@Orionsg I agree. If it is an ABL command, this awesome Plugin has to understand.

**Comment by chriscamicas** [comment] 2018-05-22 08:28
Thanks everyone for this report and analysis.
Currently, this plugin doesn't really implement indentation and formatting, it simply tells VSCode what is a "block of code".
It uses the `vscode-abl\language-configuration.json` file, and I only provided VScode with the information a block starts with `:` and ends with `end` statement.
Unfortunately, `:` is also used for string attributes, that causes VSCode to misunderstand it for a code block.
See documentation here https://code.visualstudio.com/docs/extensionAPI/language-support
Right now, I have not identified a way to differentiate the two `:` behavior.

**Comment by TauerOne** [comment] 2019-08-12 16:55
I know this is an old thread, but I think I may have a solution if anyone is still interested.  I haven't tested it completely and I'm sure it can be made more exact, but for now it seems to be working for me.

In the language-configuration.json file, remove [":", "end"] from the brackets array and add an indentationRules object to handle code blocks.  Here is my current language-configuration.json file.

`{
    "comments": {
        // symbol used for single line comment. Remove this entry if your language does not support line comments
        "lineComment": "//",
        // symbols used for start and end a block comment. Remove this entry if your language does not support block comments
        "blockComment": [ "/*", "*/" ]
    },
    // symbols used as brackets
    "brackets": [
        ["{", "}"],
        ["[", "]"],
        ["(", ")"]
    ],
    // symbols that are auto closed when typing
    "autoClosingPairs": [
        ["{", "}"],
        ["[", "]"],
        ["(", ")"],
        ["\"", "\""],
        ["'", "'"],
        ["/*", "*/"]
    ],
    // symbols that that can be used to surround a selection
    "surroundingPairs": [
        ["{", "}"],
        ["[", "]"],
        ["(", ")"],
        ["\"", "\""],
        ["'", "'"],
        ["/*", "*/"]
    ],
    // lines that end in a colon, followed by possible white space, denote a block
    // block ends with "end." or "end" + whitespace + optional word (procedure, function, case, etc) + "."
    "indentationRules": {
        "increaseIndentPattern": "^.+:\\s*$",
        "decreaseIndentPattern": "^\\s*end(\\.|\\s+.*\\.)$"
    }
}`

**Comment by chriscamicas** [comment] 2019-08-13 07:55
Nice one @RabbitChaser, thank you !
I didn't see the addition of `identationRules` 
Just tested it, and it seems to work.
But we loose some features of the brackets like highlight closing, go to etc.
cf https://code.visualstudio.com/api/language-extensions/language-configuration-guide#brackets-definition

Why did you remove it in the brackets definition array ?
It kept it, and they work fine together. Have you noticed a possible issue there ?

**Comment by chriscamicas** [comment] 2019-08-13 08:00
Forget about my question.
A simple `'':u` messes with the brackets matching detection.
We definitely need a regex pattern for brackets to work

**Closed as completed** 2019-08-13 09:13 UTC
