### ISSUE TITLE
Support for object-oriented outlines and code completion?

### ISSUE THREAD

**Issue by dtrockel** [chriscamicas/vscode-abl#60] opened 2020-06-19 08:39 UTC
Are you guys planning on adding support for classes in the foresseable future?

I really like the extension and I'd love to use vs code as the primary IDE for my abl/progress work, but as I'm primarily working with classes / in an object-oriented way there's really some baseline utility missing for me.

Otherwise great extension!

**Comment by chriscamicas** [comment] 2021-03-15 09:52
duplicate of #61

**Closed as completed by chriscamicas** 2021-03-15 09:52 UTC
Labels: enhancement
