### ISSUE TITLE
Syntax highlighting breaks down when include contains preprocessor references

### ISSUE THREAD

**Issue by ntreeby** [chriscamicas/vscode-abl#80] opened 2022-04-25 20:27 UTC
If I have an include such as:
`{catch.i &PostAction="MESSAGE {&MessageVar}"}`

the syntax highlighting breaks down, because it doesn't recognize the nested braces inside the include.  It takes the first `}` it encounters (at the end of `{&MessageVar}`) as closing the entire include - `{catch.i .... }` - and everything after that is not highlighted correctly.

**Comment by gquerret** [comment] 2022-04-26 11:30
I'll have a look, but can't promise anything as I've never touched the TextMate grammar, and also because the risk of breaking something else is quite high !

**Comment by chriscamicas** [comment] 2022-04-26 13:44
There are some automated tests.
Usually when I deal with uncovered use cases, I write the test file first, and fix the failed tests (TDD approach)
The existing test suite should prevent regression 🤞 
If I may suggest a cool reading to start with TextMate grammar, it's [this one](http://www.apeth.com/nonblog/stories/textmatebundle.html)
Syntax highlighting grammar are quite different from language grammar

**Comment by chriscamicas** [comment] 2022-04-26 13:47
also the issue should be moved (or linked) to the TextMate repository https://github.com/chriscamicas/abl-tmlanguage

**Comment by chriscamicas** [comment] 2022-04-26 13:48
sounds related to https://github.com/chriscamicas/vscode-abl/issues/45

**Comment by gquerret** [comment] 2022-04-26 15:11
Thank you @chriscamicas I'll read the article !
I already had multiple issues in my lexer regarding include arguments, so I know the syntax can be really tricky. I'll probably go for something as generic as possible just to get the right position of the closing curly brace.

**Closed as completed** 2022-04-28 07:21 UTC
